const S = (category, question, answer, keywords) => ({
  category, question, answer,
  keywords: keywords.split('|').map((k) => k.trim()).filter(Boolean),
});

export const contractSeed = [
  S('commercial-contracts',
    'What makes a contract legally valid in Nepal?',
    'A contract becomes legally binding in Nepal when there is a clear offer and an acceptance that matches it, the parties have the legal capacity to contract, something of value is exchanged, and the purpose is lawful. Clarity of terms matters most of all: if the parties did not truly agree on the essentials of the deal, there is little for a court to enforce. A written agreement is not always mandatory, but it is far easier to prove and to enforce than a verbal one. We draft and review agreements so the terms are complete and workable, which is what gives a contract real force in practice.',
    'what makes a contract valid nepal|valid contract requirements|legally binding agreement kathmandu'),
  S('commercial-contracts',
    'When should I put an agreement in writing instead of a handshake deal?',
    'Write it down whenever money, property, a long relationship, risk or another person is involved. The difficulty with a verbal agreement is not that it is unenforceable, but that a detail is remembered differently between the parties and there is nothing to compare against. The real purpose of a written contract is to prevent the dispute by recording what was actually agreed, including price, scope, dates and what happens if a party does not perform. We convert handshake relationships, common in Nepali business, into documented, enforceable terms without over-engineering them, so the business is protected without losing the speed of a handshake culture.',
    'verbal vs written contract nepal|when to use a written contract|enforceable agreement clear terms'),
  S('commercial-contracts',
    'What should a service agreement include in Nepal?',
    'A service agreement should define the service: the deliverables, the scope and its boundaries, the standard and timeline expected, the fee and how it is paid, and how changes to scope are handled. It should also state who owns any intellectual property created in the deliverables, what is confidential, whether the provider is an independent contractor, and how the agreement is ended. The most frequent disputes in services concern scope, not price, so a clear boundary prevents that. We prepare service agreements that are clear about what is and is not included, so both parties agree on value from the start rather than discovering differences at delivery.',
    'service agreement nepal|service contract contents|professional services agreement kathmandu'),
  S('commercial-contracts',
    'How do I draft a contract that protects my business in Nepal?',
    'A protective contract defines the deal precisely and sets fair rules for when something goes wrong. The provisions that protect you most are the exact scope and price, payment terms with a consequence for non-payment, warranties, a limitation of liability, confidentiality and intellectual property ownership, and termination with clear notice. Every clause must also be realistic to enforce; a clause no party will accept, or one a court will not uphold, is worth nothing. It is less about loading in extra clauses and more about drafting the right ones so they are consistent and lawful under Nepali law. We draft and review contracts with your actual exposure in mind.',
    'draft a contract that protects you|commercial contract clauses nepal|contract protection drafting'),
  S('joint-ventures',
    'What is a shareholder agreement and do I need one?',
    'A shareholder agreement is a private contract between the owners of a company that sets out, alongside the company articles, how they will run the business and control it: who may join, which decisions require consent or a veto, how shares may be transferred and who has a first right to buy them, how further capital is raised, and what happens on exit. It is the practical document that prevents disputes between two or more owners, because it records the ground rules before there is disagreement. Any company of more than one owner can be protected by such an agreement. We draft shareholder agreements tailored to each owner situation.',
    'shareholder agreement nepal|need a shareholders agreement|shareholders agreement protection'),
  S('joint-ventures',
    'What should a founders agreement cover?',
    'A founders agreement records how the people starting a company will own and run it: the division of shares at the start, how the founders earn out their equity as they keep working (vesting), what happens if a founder leaves, how decisions are made, how the business idea and confidential information are protected, and the commitment expected of each founder. Without one, the most common failure relates to what was least discussed at the start: what happens when one person leaves. Written and agreed while there is goodwill, it protects the business and gives present and future investors confidence in how the team holds together. We help founders record these basics cleanly.',
    'founders agreement nepal|founder equity vesting|startup founders document'),
  S('mna',
    'What is legal due diligence and why is it important before buying a business?',
    'Legal due diligence is the process of checking a company before you buy into it or acquire it, so you find out what you are actually getting and negotiate accordingly. When you buy the shares of a company you inherit the company as it is, including its liabilities and risks, not just what looks good. Diligence examines ownership and title, the key contracts, employees, taxes, intellectual property, claims and the registration of the company. Hidden problems, most commonly tax liabilities or gaps in ownership, are normal almost exactly where diligence would have exposed them. Buyers use it to adjust price or walk away; sellers use a careful process to close cleanly.',
    'legal due diligence nepal|due diligence before buying|legal due diligence checklist'),
  S('mna',
    'What is the difference between buying shares and buying assets in Nepal?',
    'Buying shares of a company means the buyer takes the place of the seller as shareholder and acquires the company itself along with all its assets, contracts and obligations, whether they are listed or not. Buying assets means the buyer acquires only the specific assets of the business and, done carefully, can avoid taking on general liabilities and tax exposure of the company. The two routes differ in tax treatment, in the approvals they need and in which risk sits with the buyer and seller. This structural decision is made first, because it determines the documentation that follows. We help parties choose and draft the structure that best fits the risk and the commercial goal.',
    'share sale vs asset sale nepal|buy shares vs buy assets|how to buy a company nepal'),
];