const S = (category, question, answer, keywords, featured = false) => ({
  category, question, answer,
  keywords: keywords.split('|').map((k) => k.trim()).filter(Boolean),
  featured,
});

/**
 * FAQs covering the newer "Our Services" practice groups (family, criminal,
 * NGO/INGO, international clients, technology) so the knowledge centre spans
 * the full service catalogue.
 */
export const serviceSeed = [
  S('family-law',
    'How do I register a marriage in Nepal?',
    'Marriage registration in Nepal is carried out at the ward office (Ward Office / local registration office) where the marriage takes place, under the Civil Registration Act. Both spouses attend with their citizenship certificates and, depending on the office, any required witnesses. A court marriage follows a different route through the district court. If the marriage took place abroad, registration arrangements differ and require authentication of foreign documents. Because requirements can vary by office and by situation, we help confirm the right process, prepare the application and accompany you so the registration is accepted the first time.',
    'marriage registration nepal|register marriage kathmandu|court marriage nepal', false),
  S('family-law',
    'What is the divorce process in Nepal?',
    'Divorce in Nepal is filed at the family court within the district court of the respondent\'s locality. A mutual divorce — where both spouses agree on the divorce and its terms — is the faster route and is typically finalised after the statutory cooling period. A contested divorce is heard and decided by the court over a longer period. The court also decides custody, maintenance and division of property. Legal representation ensures the petition, evidence and negotiations are handled correctly, and that custody and maintenance are addressed properly from the start rather than argued over later.',
    'divorce process nepal|mutual divorce kathmandu|how to get divorce in nepal', false),
  S('family-law',
    'How is child custody decided in Nepal?',
    'Nepali courts decide custody primarily in the interest of the child, considering the child\'s welfare, age and the capacity of each parent to care for the child. Very young children are usually placed with the mother unless there are compelling reasons otherwise, though the court examines the individual facts of each case. Custody can be decided during a divorce or separation matter and can later be revisited if circumstances change materially. We advise parents on realistic expectations, negotiate custody and access arrangements, and present the evidence a court needs to reach a decision that protects the child\'s stability.',
    'child custody nepal|divorce custody kathmandu|who gets custody in nepal', false),
  S('family-law',
    'Can I adopt a child in Nepal?',
    'Adoption in Nepal is governed by the National Code and adoption rules, and the process runs through the authorised agencies and, for intercountry adoption, the Ministry of Women, Children and Senior Citizens. Domestic adoption requires eligibility assessment, matching, and court approval; intercountry adoption is more heavily regulated and involves coordination with the competent authorities. The process is deliberately thorough to protect children. We guide prospective parents through eligibility, documentation and the approvals, and help ensure the adoption is lawful and complete.',
    'adoption nepal|adopt a child kathmandu|adoption process in nepal', false),
  S('family-law',
    'How do I claim my share of family or inherited property in Nepal?',
    'Under the National Civil Code, rights to ancestral and self-acquired property follow defined shares. If a share is not being honoured, the first practical step is usually a negotiated settlement or a lawyer\'s letter, and if that fails, a partition claim in court. Partition cases can run for years, so it is worth resolving entitlement clearly and early. We help you establish your claim, document it, and either negotiate a family settlement or pursue a court partition efficiently.',
    'partition property nepal|inheritance share nepal|family property claim kathmandu', false),

  S('criminal-law',
    'What should I do if I am arrested in Nepal?',
    'If you are arrested in Nepal, you have the right to know the reason for your arrest and the right to a lawyer. You should remain calm, avoid making statements beyond the basic details, and ask to contact a lawyer and your family as soon as possible. Anyone detained must be brought before a judicial authority within the time limits the law sets. Engaging a defence lawyer early is the single most important step: counsel protects your rights at every stage, from the initial detention through bail and the court process, and helps you avoid statements that could be used against you later.',
    'arrested in nepal|rights when arrested kathmandu|what to do if detained nepal', false),
  S('criminal-law',
    'How do I apply for bail in Nepal?',
    'Bail is requested before the court handling the matter, and the court decides based on the nature of the offence, the evidence, the risk of absconding and whether the accused will interfere with witnesses. For minor offences bail is usually granted; for serious offences it may be opposed. The application and any opposition should be grounded in the specific facts and law. We prepare the bail application, present the arguments, and if bail is refused, consider the available review or appeal options so a detained client is not left without a path forward.',
    'bail application nepal|how to get bail kathmandu|bail in nepal', false),
  S('criminal-law',
    'What counts as white-collar or financial crime in Nepal?',
    'White-collar crime covers fraud, embezzlement, forgery, money laundering, tax evasion, and offences under the Anti-Money Laundering Act and related laws. These matters often straddle civil and criminal law: a company may face regulatory penalties while individuals face criminal charges. Because the evidence is documentary and technical, an early and detailed defence is essential. We help both companies and individuals respond to investigations, protect records and rights, and defend or resolve matters before regulators and the courts.',
    'white collar crime nepal|fraud nepal law|money laundering defence kathmandu', false),
  S('criminal-law',
    'Can a company be charged with a crime in Nepal?',
    'Yes. Nepali law allows corporate bodies to be held criminally liable for certain offences, and the same facts can also expose directors and officers personally. A corporate criminal case may arise from fraud, environmental, tax or regulatory offences. Companies facing investigation should respond strategically: preserve documents, cooperate within legal limits, and defend the entity while protecting the position of individual officers. We advise companies on how to manage an investigation, negotiate with authorities and, where appropriate, defend the charges in court.',
    'corporate crime nepal|company criminal liability|corporate fraud investigation nepal', false),
  S('criminal-law',
    'How long can police hold a suspect before charges in Nepal?',
    'The law sets time limits for holding a suspect before a decision to charge is made, and the exact limit depends on the nature and gravity of the alleged offence. A detained person must be produced before a judicial authority within the legal limit, and continued detention requires lawful extension. If the limit is exceeded, the detention can be challenged. We track these deadlines closely on behalf of clients and act immediately if they are breached, so a client\'s liberty is protected through proper process rather than by delay.',
    'police custody time nepal|detention limit nepal|suspect rights kathmandu', false),

  S('nonprofit',
    'How do I register an NGO in Nepal?',
    'An NGO in Nepal is registered either with the District Administration Office (DAO) for local NGOs or with the Social Welfare Council for organisations working at a wider or international scale. The registration requires a governing body, a constitution, and the completed applications, followed by affiliation with the Social Welfare Council. After registration, an NGO must file annual reports and renewals to stay compliant. The choice of where to register depends on your scope and funding sources, and getting the structure right at the start avoids compliance problems later. We prepare the constitution and documents and manage the registration from start to finish.',
    'register ngo nepal|how to register an ngo kathmandu|ngo registration process', false),
  S('nonprofit',
    'What compliance does an INGO need in Nepal?',
    'INGOs operate in Nepal under an agreement with the Social Welfare Council and must comply with annual reporting, project approval, and the requirement to route funds through approved arrangements. Their local partners (NGOs) are similarly required to report. Compliance is enforced through renewals and project approvals, so an INGO that falls behind can find its operations interrupted. We help INGOs and their local partners keep agreements current, file reports on time and resolve any compliance gaps before they become a problem.',
    'ingo compliance nepal|ingo regulations kathmandu|social welfare council ingo', false),
  S('nonprofit',
    'Can foreigners register an NGO in Nepal?',
    'Foreign nationals generally cannot register a local NGO in Nepal in their own name in the same way as citizens; the established route is an INGO approved through the Social Welfare Council, working with local partner NGOs. The legal structure, staffing and funding flows must comply with the relevant rules. This area is specific and rule-heavy, so it is worth confirming the current policy with a lawyer before committing. We explain the workable structures, advise on the INGO agreement route and help you structure the operation lawfully.',
    'foreigners ngo nepal|foreigner register ngo|international ngo nepal', false),

  S('nrn',
    'Can a non-resident Nepali (NRN) invest in Nepal?',
    'Yes. Non-resident Nepalis can invest in Nepal under the foreign investment framework, and NRNs benefit from the same investment rules as other foreign investors, with some concessions. The investment can be in equity of a new or existing company or in a listed company, subject to sector eligibility and the minimum investment thresholds under FITTA. NRN investment follows the foreign investment approval route, and depending on the sector, may require local partners. We help NRN investors confirm eligibility, choose the right structure and complete both investment approval and company registration.',
    'nrn invest nepal|nrn investment company|non resident nepali investment', false),
  S('nrn',
    'How can I set up a business in Nepal from abroad?',
    'Setting up a business in Nepal from abroad is possible, but it requires coordinating company registration, PAN, and any foreign investment approval, and much of this needs in-country steps. A common approach is to structure the company, prepare all documents remotely, and authorise a local representative through a power of attorney to complete filings. Foreign investors also need to plan their capital remittance and banking carefully. We manage the entire process on your behalf — documentation, filings and approvals — so you can incorporate and open the business without unnecessary travel.',
    'set up business nepal from abroad|foreign investor company nepal|open company remotely nepal', false),
  S('nrn',
    'What is the minimum foreign investment amount in Nepal?',
    'The Companies Act and the foreign investment framework set a minimum foreign investment amount for equity participation, and it applies to most foreign investments under FITTA. The threshold is revised from time to time and can vary with the sector. A foreign investor also needs the investment to fall within an eligible sector. Because the exact figure and rules change, we confirm the current minimum before you commit, and structure the investment so the amount and structure satisfy both the FITTA requirement and company law.',
    'minimum foreign investment nepal|fdi threshold nepal|fitta minimum investment', false),
  S('nrn',
    'Do foreign investors need a local partner in Nepal?',
    'Not always. Nepal allows wholly foreign-owned companies in many sectors, so a local partner is not required by law across the board. However, certain sectors are reserved for Nepali citizens or businesses, and in those sectors a foreign investor needs a Nepali partner or cannot invest at all. Beyond legal requirements, a local partner can bring market access and practical advantages. We assess your sector and objectives, confirm whether a partner is required or advisable, and structure the arrangement accordingly.',
    'foreign investor local partner nepal|joint venture foreign nepal|wholly foreign owned company nepal', false),

  S('technology',
    'Is there a data protection law in Nepal?',
    'Nepal does not yet have a single comprehensive data protection statute, but privacy protections exist under the Constitution, the Electronic Transactions Act (relating to unauthorised access and breaches) and sector-specific rules, and a dedicated privacy framework has been under development. In practice this means businesses should still treat customer and employee data carefully: disclosure, retention and breach handling carry legal risk under existing laws. We help companies build practical privacy policies and data-handling practices that hold up under the current law and are ready for the emerging framework.',
    'data protection law nepal|privacy law kathmandu|electronic transactions act data', false),
  S('technology',
    'Is it legal to use e-signatures on contracts in Nepal?',
    'Electronic signatures and records are recognised under the Electronic Transactions Act, with digital signatures issued by approved certifying authorities carrying the strongest legal standing. The acceptability of an electronic signature depends on the type of document and how it is authenticated. Routine commercial agreements can generally be signed electronically, while some documents still require physical signatures, notarisation or registration. We review your agreement and advise on the most reliable signing route so it is enforceable when it matters.',
    'digital signature nepal|e signature legal nepal|electronic signature contracts', false),
  S('technology',
    'What should a software or IT agreement cover?',
    'An IT or software agreement should clearly define the scope, deliverables, ownership of the code and intellectual property, licences, payment, confidentiality, data handling, warranties, liability caps, and how disputes are resolved. The two areas that most often cause trouble are IP ownership — whether the client owns the code and materials — and data/confidentiality. Getting these terms right at the start prevents renegotiation and disputes. We draft and review software, SaaS, licensing and consulting agreements so both the business terms and the legal risk are properly covered.',
    'software agreement nepal|it contract drafting|saas agreement kathmandu', false),
  S('technology',
    'What can I do if someone commits cyber crime against my business?',
    'Unauthorised access, data interference, fraud and electronic forgery are offences under the Electronic Transactions Act, and a business affected by cyber crime can file a complaint with the Nepal Police\'s cyber bureau and pursue criminal remedies, alongside any civil claims. The evidence trail — logs, timestamps, access records — is usually decisive, so the system should be preserved quickly. We help you respond without destroying evidence, file the complaint, coordinate with investigators, and pursue the legal remedies available.',
    'cyber crime nepal|cyber bureau complaint|hacking report nepal', false),

  S('property',
    'How do I verify land ownership before buying in Nepal?',
    'Land verification in Nepal involves checking the land record (kitta) at the land revenue office for the actual owner, the land category, encumbrances such as mortgages, and any government restrictions on the plot. Ownership records can be misleading on their own, so a physical and record check is essential, and a purchase should be documented through a sale deed with the required valuation and registration. We conduct the verification, flag risks before you commit and handle the deed and registration process so your title is clean.',
    'verify land ownership nepal|land kitta check|buy property safely kathmandu', false),
  S('property',
    'Can foreigners buy property in Nepal?',
    'In general, foreigners cannot own land or property in Nepal in their own name; land ownership is restricted to Nepali citizens. There are, however, recognised structures for foreign-invested businesses to use property for their operations, such as leasing or obtaining land through a licensed corporate entity in eligible circumstances. These structures are specific and regulated. We explain what is genuinely possible for your situation — ownership, lease or corporate holding — and keep the arrangement lawful.',
    'can foreigners buy property nepal|foreigner land ownership nepal|foreign company property nepal', false),
  S('property',
    'What is the process for transferring property in Nepal?',
    'Property transfer in Nepal requires a sale deed, calculation and payment of registration fees and capital gains tax, and registration at the relevant land revenue or malpot office. The transfer is final when the deed is registered and the records updated. Both buyer and seller should verify the title and tax position before signing, because the liabilities attach to the parties and to the land. We prepare the deed, verify the records, calculate the taxes and complete the registration on your behalf.',
    'property transfer nepal|land registration process|sale deed kathmandu', false),

  S('employment',
    'Can I terminate an employee without notice in Nepal?',
    'Under the Labour Act, an employer can only terminate employment for a justified reason and through the proper procedure; ending employment without notice or cause exposes the employer to compensation and reinstatement claims. Certain serious misconduct can justify dismissal, but the process — investigation, opportunity to respond and documentation — must be followed. A termination done badly usually costs more than doing it properly. We advise employers on lawful grounds, help run the process cleanly, and prepare the documentation that protects the company if the decision is later challenged.',
    'terminate employee nepal|employee dismissal kathmandu|labour act termination', false),
  S('employment',
    'What must an employment contract in Nepal include?',
    'A proper employment contract in Nepal should state the role, remuneration, working hours, leave, termination and notice terms, and any specific conditions of employment, aligned with the Labour Act\'s requirements for employment records and contracts for fixed-term or foreign workers. The contract also needs to handle confidentiality, IP and restrictions where relevant. A clear contract prevents most workplace disputes, and where one is missing, the law still implies many obligations. We draft contracts for employers and review them for employees so both sides know exactly where they stand.',
    'employment contract nepal|labour contract kathmandu|employee agreement nepal', false),
  S('employment',
    'What are an employer\'s duties under the Labour Act?',
    'The Labour Act sets out core employer duties: written employment records and contracts, payment of remuneration and statutory benefits (gratuity, provident fund, leave), a safe workplace, and compliance with termination and redundancy procedures. It also regulates working hours, overtime and the treatment of foreign workers. Non-compliance can lead to fines, employee claims and adverse findings in disputes. We run compliance reviews for employers, draft the required policies and records, and help fix gaps before they surface in a claim or inspection.',
    'employer duties nepal|labour act compliance|worker rights nepal', false),

  S('licensing',
    'What licences does my business need to operate in Nepal?',
    'Most businesses need PAN registration and, where turnover or activity requires it, VAT registration. Beyond those, the licences depend on your industry: an operating or sector licence from the relevant ministry or authority, and for some activities municipal permits as well. Industries such as hospitality, health, finance, education and manufacturing each have specific requirements. Operating without the required licence can mean fines or closure. We map your activity to the licences required, prepare the applications and manage renewals.',
    'business licence nepal|trade license kathmandu|operating permit nepal', false),

  S('debt-recovery',
    'How can I recover money owed to my business in Nepal?',
    'Recovery usually starts with a formal demand letter, which often resolves the matter quickly, and moves to legal proceedings if payment is not made. Under the laws on money recovery, a creditor can pursue the debt through the courts, and well-documented transactions with clear contracts, invoices and acknowledgements are far easier to enforce. Timing matters: acting promptly and preserving evidence improves your position. We issue the demand, assess the debtor\'s position, and pursue the most effective recovery route — settlement, court claim or enforcement.',
    'recover debt nepal|money recovery kathmandu|demand letter nepal', false),
  S('debt-recovery',
    'Can I recover debts without going to court in Nepal?',
    'Yes — many debts are recovered without a court claim. A professionally drafted demand letter frequently produces payment or a negotiated schedule, and mediation or arbitration under a contract can resolve the matter if the agreement provides for it. Where a settlement is agreed, recording it properly makes it enforceable. We help you press for payment through the right channels, and only escalate to court when the realistic alternatives have been exhausted, so legal costs stay proportionate.',
    'recover debt without court|debt settlement nepal|mediation debt recovery', false),

  S('securities',
    'How can my company raise investment in Nepal?',
    'A company can raise capital through equity (new shareholders, venture or angel investment, or a public issue), debt, or instruments like convertible notes. Private investment in a private company follows company law and the shareholders\' agreement; a public issue is regulated by SEBON and is a heavier process. Structuring the round — valuation, dilution, rights and the agreement — matters more than most founders expect. We help you structure and document private investment rounds cleanly and navigate the regulatory path if you plan a public listing.',
    'raise investment nepal|equity funding kathmandu|seed round company nepal', false),
  S('securities',
    'What are the compliance requirements for a listed company in Nepal?',
    'A listed company must comply with SEBON\'s continuing disclosure rules: periodic financial reporting, material event disclosures, and corporate governance requirements, alongside company law compliance. Failing to disclose or filing late can draw penalties and affect the company\'s market standing. The obligations begin before listing and continue throughout. We help companies prepare for listing, manage the disclosure calendar and respond to SEBON queries so compliance never becomes a liability.',
    'listed company compliance nepal|sebon rules|public company disclosure', false),

  S('documents',
    'How do I get a power of attorney in Nepal?',
    'A power of attorney authorises someone to act on your behalf and can be granted in Nepal, or before a Nepali diplomatic mission if you are abroad. It is most reliable when notarised or witnessed and, for property and court matters, may need to meet specific formalities. Whether the POA must be registered depends on the purpose. We prepare the power of attorney with the correct scope and formalities, so the document is accepted by banks, offices and courts when it is needed.',
    'power of attorney nepal|poa kathmandu|general power of attorney', false),
  S('documents',
    'Do I need my documents notarised for use abroad?',
    'Whether a document needs notarisation, legalisation or an apostille for use abroad depends on the country you are sending it to and the purpose. Many countries require legalisation by the Nepali Ministry of Foreign Affairs and the receiving country\'s embassy, and for members of the apostille convention, a simpler apostille process. Getting the chain wrong means the document is returned. We confirm the exact requirement for your destination, notarise and legalise the document, and arrange translation where needed.',
    'apostille nepal|document legalisation|notarize documents kathmandu', false),

  S('advisory',
    'Do I really need a lawyer on retainer for my business?',
    'A retainer gives your business prompt access to legal advice on day-to-day matters — contracts, compliance, employment, disputes — before small issues become expensive ones. For most companies, the cost of a retainer is repaid the first time it prevents an unfavourable contract clause, a compliance fine or a lawsuit. Retainers can be sized to your activity, from a simple monthly advisory to full support. We structure retainers so you get responsive, senior advice at a predictable cost, and can flex it up for larger transactions or disputes.',
    'legal retainer nepal|business lawyer on retainer|corporate advisory kathmandu', false),
];
